language: java
branches:
  only:
   - master
sudo: false
cache:
  directories:
    - "$HOME/.m2"
notifications:
  email: hacksoldier93@gmail.com
  on_failure: never
env: GDAL_LIBRARY_NAME=disabled_see_geot-4733
os:
  - linux
  - osx
  - windows
matrix:
  allow_failures:
    - os: osx
  include:
   - os: linux
     jdk: oraclejdk8