language: java

branches:
  only:
   - master

sudo: false
cache:
  directories:
    - "$HOME/.m2"
language: java
script:
  - mvn -B -T2 -fae -Djava.awt.headless=true -Dall clean install
notifications:
  email: false
  on_failure: never
env: GDAL_LIBRARY_NAME=disabled_see_geot-4733
os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
  include:
   - os: linux
     jdk: oraclejdk8